repos:
    - repo: https://github.com/timothycrosley/isort
      rev: 5.10.1
      hooks:
          - id: isort

    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
          - id: black

    - repo: https://github.com/pycqa/flake8
      rev: 4.0.1
      hooks:
          - id: flake8
            additional_dependencies:
                [
                    flake8-bugbear==22.6.22,
                    flake8-builtins==1.5.3,
                    flake8-comprehensions==3.10.0,
                    flake8-deprecated==1.3,
                    flake8-docstrings==1.6.0,
                    flake8-eradicate==1.2.1,
                    flake8-plugin-utils==1.3.2,
                    flake8-polyfill==1.0.2,
                    flake8-pytest-style==1.6.0,
                    flake8-simplify==0.19.2,
                ]

    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.4
      hooks:
        - id: bandit
          exclude: test_crazy_turtle.py

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: "v0.961"
        hooks:
        -   id: mypy
            args: [--strict]
