name: Test

on:
  workflow_dispatch:

  push:
    branches:
      - main

concurrency: 
  group: test${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11-dev']
    steps:
      - name: Check out Respository
        uses: actions/checkout@v3

      - name: Setup up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      
      - name: Display python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-black flake8-isort bandit mypy pytest

      - name: Lint with flake8
        if: ${{ always() }}
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Static type check with mypy
        if: ${{ always() }}
        run: |
          mypy --strict .
      
      - name: Testing with pytest
        if: ${{ always() }}
        run: |
          pytest test_crazy_turtle.py -n auto

      - name: Security check with bandit
        if: ${{ always() }}
        run: |
          bandit
